### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by bonimy** [bonimy/MushROMs#1]
# Things to do before diving into the project
We need a good guideline for building this project. Too many times have I let myself focus so much on writing code and never maintaining it that it always ends up an unmanageable beast. Below is a short list of things to do before submitting contributions.
## Task List
- [x] - Build a README file (#3)
- [x] - Code of Conduct (#2)
- [x] - Issue Template
- [x] - Pull Request Template
- [x] - Contributing
- [x] - Set up Visual Studio
- [x] - Establish code formatting rules
- [x] - Outline project goals
### Build a README file
The README is the front page of project and therefore the first impression of what it can do for them. Ideally, I'd like the format of our README to follow [GitHub's suggested guidelines](https://guides.github.com/features/wikis/#Formatting-a-readme). Note this is a documentation for the source code of the project itself, not the deployed product. More information provided in #3.
### Code of conduct
Establishing a good code of conduct is a big deal to me and I want it to be to all contributors too. GitHub offers a few ready-made CoCs to use and one of these might work fine.
### Contributing
I want a separate document that covers what would be most helpful for people who want to add to the project. I have a working outline of this right now but it's fairly extensive and could take some time to complete. This one ultimately needs to be done before any code can be added since in it I plan to define code formatting rules to maintain readability for everyone and minimize confusing changes in styles between contributors.
### Set up Visual Studio
I want this to be a cross-platform product, but I only have the resources to work on Windows 10 Desktop right now. My IDE of choice will be Visual Studio 2017 (or latest). Setting up new IDEs should be their own Issues when a contributor wants to add one.
### Establish code formatting rules
This is mentioned in the Contributing section already, but it deserves more emphasis. Everyone likes to write code differently and, if the projects grows, it can get out of hand. So well-defined styles are essential as early as possible. This mostly emphasizes whitespace rules, bracket placement, class design, and test development. Maybe other things too that I can't think of right now.
### Outline project goals
I want to open up issues that state the features that need to be added to our project. When an issue is opened, we should try to best defined what the features does, doesn't do, how to best separate components, and what tests can guide us in designing this feature. I'm aiming for test-driven-development, so the last requirement will be the most essential. I already have a lot of ideas about the project, so I'd like to create one _task list_ Issue that addresses what I currently have in mind, and then make individual issues from that list.

**Comment by bonimy** [comment]
Closing this issue now that every task has been discussed an issue.
