### ISSUE TITLE
Establish code formatting rules

### ISSUE THREAD

**Issue by bonimy** [bonimy/MushROMs#16]
# Issue
The project doesn't have a set of guidelines for formatting code.

# Features
>Coding conventions serve the following purposes:
>
>* They create a consistent look to the code, so that readers can focus on content, not layout.
>* They enable readers to understand the code more quickly by making assumptions based on previous experience.
>* They facilitate copying, changing, and maintaining the code.
>* They demonstrate C# best practices.
> 
> -[Microsoft C# Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions)

# Resolution/Bug tracking progress
We will follow the guidelines provided in the [Microsoft C# Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions). We may have to make minor changes. The task list outlines which sections are under review before submitting code format guidelines.

# Task List
**Sections for review**:
- [x] - Naming Conventions
- [x] - Layout Conventions
- [x] - Commenting Conventions
- [x] - Language Guidelines
    - [x] - String Data Type
    - [x] - Implicitly Typed Local Variables
    - [x] - Unsigned Data Type
    - [x] - Arrays
    - [x] - Delegates
    - [x] - try-catch and using Statements in Exception Handling
    - [x] - && and || Operators
    - [x] - New Operator
    - [x] - Event Handling
    - [x] - Static Members
    - [x] - LINQ Queries

**Code style**:
- [ ] - General
- [ ] - Formatting
    - [ ] - General
    - [ ] - Indentation
    - [ ] - New Lines
    - [ ] - Spacing
    - [ ] - Wrapping
- [ ] - Naming
