### ISSUE TITLE
Add Helper files

### ISSUE THREAD

**Issue by bonimy** [bonimy/MushROMs#23]
# Issue
A lot of the files from the archival [Helper](https://github.com/bonimy/MushROMs-2017-Archive/tree/master/Helper) project are complete and usable in their current stage. It would be helpful to add them since they will get a lot of use.

# Resolution
Some of the files are already fully documented and include unit tests. These can be added right away. Others are useful but lack documentation or unit tests. Those should be updated then added.

# Task List
- [x] - [PixelFormats](https://github.com/bonimy/MushROMs-2017-Archive/tree/master/Helper/PixelFormats)
  - [ ] - Readme file
  - [ ] - [BitArray.cs](https://github.com/bonimy/MushROMs-2017-Archive/blob/master/Helper/PixelFormats/BitArray.cs)
  - [x] - [Color15BppBgr.cs](https://github.com/bonimy/MushROMs-2017-Archive/blob/master/Helper/PixelFormats/Color15BppBgr.cs)
  - [x] - [Color24BppBgr.cs](https://github.com/bonimy/MushROMs-2017-Archive/blob/master/Helper/PixelFormats/Color24BppRgb.cs)
  - [x] - [Color32BppBgr.cs](https://github.com/bonimy/MushROMs-2017-Archive/blob/master/Helper/PixelFormats/Color32BppArgb.cs)
- [x] - Properties
  - [x] - Resources
  - [x] - Strong name key
- [x] - [AssertDictionary.cs](https://github.com/bonimy/MushROMs-2017-Archive/blob/master/Helper/AssertDictionary.cs)
- [x] - [BlendMode.cs](https://github.com/bonimy/MushROMs-2017-Archive/blob/master/Helper/BlendMode.cs)
- [x] - [ColorF.cs](https://github.com/bonimy/MushROMs-2017-Archive/blob/master/Helper/ColorF.cs)
- [x] - [ExtensionComparer.cs](https://github.com/bonimy/MushROMs-2017-Archive/blob/master/Helper/ExtensionComparer.cs)
- [x] - [ExtensionDictionary.cs](https://github.com/bonimy/MushROMs-2017-Archive/blob/master/Helper/ExtensionDictionary.cs)
- [x] - [PathComparer.cs](https://github.com/bonimy/MushROMs-2017-Archive/blob/master/Helper/PathComparer.cs)
- [x] - [PathDictionary.cs](https://github.com/bonimy/MushROMs-2017-Archive/blob/master/Helper/PathDictionary.cs)
- [x] - [SR.cs](https://github.com/bonimy/MushROMs-2017-Archive/blob/master/Helper/SR.cs)
- [x] - [SubstringPointer.cs](https://github.com/bonimy/MushROMs-2017-Archive/blob/master/Helper/SubstringPointer.cs)
- [x] - [SuffixTree.cs](https://github.com/bonimy/MushROMs-2017-Archive/blob/master/Helper/SuffixTree.cs)

**Comment by bonimy** [comment]
I should add the readme to this and it should be all done.
