### ISSUE TITLE
Issues that need to be written out

### ISSUE THREAD

**Issue by bonimy** [bonimy/MushROMs#36]
## Issue
This just outlines a list of issues I still need to create. I'll add things as they come, to help me not forget.

## Task List
- [ ] - Document SMB2 (J) level format
- [ ] - Document SMB2 (U) level format
- [ ] - Document SMB3 level format
- [ ] - Separate some unit tests that test multiple methods/constructors/paths
- [ ] - Create Palette stuff
- [ ] - Create GFX stuff
- [ ] - Create Map8 and Map16 stuff
- [ ] - Create common controls
