### ISSUE TITLE
Making a CONTRIBUTING file

### ISSUE THREAD

**Issue by bonimy** [bonimy/MushROMs#6]
# Issue
Our project needs a thorough outline that details how contributions can best be submitted.
# Features
> A CONTRIBUTING file tells your audience how to participate in your project.
> -[Open Source Guides](https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines)
# Resolution
I'm using the following resources to guide in designing a CONTRIBUTING file
* [Writing your contributing guidelines](https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines)
* [Contributing Template](https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md)
* [Mozilla Contributing Guidelines](http://mozillascience.github.io/working-open-workshop/contributing/)

Our CONTRIBUTING file should have the following sections
## Warm Welcome
Thank the user for wanting to contribute to the project, and state the importance of getting to know the contributing guidelines
### How to file bug reports
We should probably make a template for this. Important things to add would be
* How to reproduce the bug
* A stack trace if available
* Screenshots if applicable
### How to suggest a new feature
I'm not too sure where to take this one immediately. An issue template could help. One of the biggest problems is like "You should add support for X" where is very large and no extra information is given. So I guess a suggestion should be as detailed as the feature is large.
### How to set up your environment and run tests
Provide a thorough guide on how to get started, successfully build the code, and run all tests to make sure they have a properly configured environment.
### Code styles
I would like to have a set of enforceable code styles to avoid conflicting formatting styles from separate contributors.
### The types of contributions we're looking for.
Basically. We want to keep it within the scope of what our project actually does. The ambition is to have it do a lot, but we need to define set goals for it. Adding a VISION file (#5) could be a good idea.
### Our vision for the project
Give a brief description of what it is we're doing. Link to possible VISION file (#5).
### How to get in contact
Provide an escalation tree for users to get in contact with me over any questions
1 Read the FAQ (when we make one)
2 Read full documentation referenced in FAQ (if applicable)
3 Submit an Issue (if applicable)
4 Contact via email (include in email why 1-3 did not help).
Mention median response time.
# Task List
- [x] - Warm Welcome
- [x] - How to file bug reports
- [x] - How to suggest a new feature
- [ ] - How to set up your environment and run tests
- [ ] - Code styles
- [x] - The types of contributions we're looking for
- [ ] - Our vision for the project
- [ ] - How to get in contact
